[package]
name = "foundry-macro-html"
version = "0.1.0"
authors = ["Oliver Moss <moss.oliver@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro-hack = { version = "0.5" }
